In [66]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

In [67]:
df = pd.read_csv('../input/airbnbopendata/Airbnb_Open_Data.csv')
df.head()

/opt/conda/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3552: DtypeWarning: Columns (25) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN

In [68]:
columns = ['id',
           'host id',
           'host_identity_verified',
           'neighbourhood group',
           'neighbourhood',
           'country', 
           'service fee',
           'minimum nights',
           'number of reviews',
           'reviews per month',
           'review rate number',
           'calculated host listings count',
           'availability 365',
           'house_rules']

In [69]:
df = df[columns]

In [70]:
df.isna().sum()

id                                    0
host id                               0
host_identity_verified              289
neighbourhood group                  29
neighbourhood                        16
country                             532
service fee                         273
minimum nights                      409
number of reviews                   183
reviews per month                 15879
review rate number                  326
calculated host listings count      319
availability 365                    448
house_rules                       52131
dtype: int64

In [71]:
df=df.dropna()

In [ ]:
df.sum()

In [ ]:
df['review rate number'].unique()

In [ ]:
plt.plot(df['review rate number'].value_counts())
plt.ylabel('review rate number')
plt.show()

In [ ]:
df['review rate number'].value_counts().plot().bar()

In [ ]:
fig, ax = plt.subplots()
ax.scatter(df['review rate number'], df['service fee'].to_string)

ax.set_xlabel('review rate number', fontsize=15)
ax.set_ylabel('review rate number', fontsize=15)

ax.grid(True)
fig.tight_layout()

plt.show()